### ISSUE TITLE
Installation issues.  estimate-ngram: command not found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mitlm/mitlm#49]
```
1. I decompressed the mitlm-0.4.1.tar.gz file on OSX Yosemite

From Terminal:
2.  ./compile.
3.  make -j

Error:
Input is: estimate-ngram -text mysent.txt -write-lm  mysent.lm
But then I get: estimate-ngram: command not found



```

Original issue reported on code.google.com by `vis...@gmail.com` on 19 Jun 2015 at 9:31

**Comment by giuliopaci** [comment]
I see several potential explanations about the issues:

1. make install is missing;
2. libmitlm.so is not in the library path (see LD_LIBRARY_PATH or DYLD_LIBRARY_PATH environment variables): this is typical if you do not install mitlm or if you install it in not standard locations (e.g.: your home instead of /usr);
3. estimate-ngram is not in your commands path (see PATH environment variable): this is typical if you do not install mitlm or if you install it in not standard locations (e.g.: your home instead of /usr).

As far as I can see this is not a mitlm issue (there is nothing we can do about it, as it depends only on user configuration), so I am closing it.
