### ISSUE TITLE
No release tarballs

### ISSUE THREAD

**Issue by davexunit** [mitlm/mitlm#54]
It would be great if this project would upload release tarballs as generated by `make dist` so that users don't need git and the autotools to get the source and bootstrap the build system.  I'd like to package this software for the GNU Guix package manager, and tarballs are preferable to git checkouts for this purpose.

**Comment by giuliopaci** [comment]
Hi, in the past there used to be tarball for mitlm. Recently we migrated to github and, as far as I know, there is no way to upload tarball. On the other hand it is possible to make release tags, so indeed my plans are to properly tag the next version of mitlm (not yet planned, unfortunately), so that there will be a downloadable tarball.

I avoided adding any tag at the moment, in order to avoid confusion with previous released tarballs. You can find an exact copy of the latest released tarball here:
https://packages.debian.org/source/experimental/mitlm

If you know any way I can add an exact copy of the tarball to github, any hints are welcome (unless it involves adding the binary file into a branch).

**Comment by davexunit** [comment]
Thanks, I'll use the Debian tarball for now.

Unfortunately, I don't think GitHub knows what `make dist` is so releases are triggered by making tags and thus distributing unbootstrapped tarballs.

**Comment by giuliopaci** [comment]
This is also my perception. I am currently thinking about maintaining a release branch, where I periodically merge the master repository and the generated files from the `make dist`. However the issue about bit-to-bit identical copies still remain. Another option could be to add a separate repository and commit the tarballs there, so that they are uploaded to a github.io page... But I do not like very much this solution.

By the way, mitlm is very under resourced at the moment. Any help in improving the tools, fixing bugs, etc. is welcome.

**Comment by davexunit** [comment]
Figured that I would mention here that I've packaged mitlm 0.4.1 for GNU Guix using the tarball from Debian.

http://git.savannah.gnu.org/cgit/guix.git/commit/?id=9698f4b74bc37439971e4b040421cc591eb1b9b7

Happy hacking!

**Comment by jwilk** [comment]
When you [create new release](https://github.com/mitlm/mitlm/releases/new), you can add arbitrary files for download.
(Personally I use [github-release](https://github.com/c4milo/github-release) instead, although its UI is rather clunky.)

**Comment by giuliopaci** [comment]
I just made a new release, attaching the source package to the release.
