### ISSUE TITLE
Error while running configure file

### ISSUE THREAD

**Issue by chvrajput** [mitlm/mitlm#65]
checking for ANSI C header files... (cached) yes
./configure: line 19521: AX_CXX_HEADER_TR1_UNORDERED_MAP: command not found
./configure: line 19522: syntax error near unexpected token `noext,'
./configure: line 19522: `AX_CXX_COMPILE_STDCXX_11(noext, optional)'

**Comment by giuliopaci** [comment]
You just need autoconf-archive macros.
Il giorno 09/ott/2017 13:04, "Chhavi rajput" <notifications@github.com> ha
scritto:

**Comment by vesis84** [comment]
Hi, I commented the two lines in `configure.ac` like this:

```
$ git diff
diff --git a/configure.ac b/configure.ac
index e964635..82c43a1 100644
--- a/configure.ac
+++ b/configure.ac
@@ -29,8 +29,8 @@ AC_PROG_LIBTOOL
 dnl Checks for header files.
 AC_CHECK_HEADERS(string.h math.h)
 AC_HEADER_STDC
-AX_CXX_HEADER_TR1_UNORDERED_MAP
-AX_CXX_COMPILE_STDCXX_11(noext, optional)
+#AX_CXX_HEADER_TR1_UNORDERED_MAP
+#AX_CXX_COMPILE_STDCXX_11(noext, optional)
```

Surprisingly, both the 'configure' and the 'compilation' went well.
Seems like the two problematic checks have become redundant 
with current compilers... (running CentOS 6.5, g++ 6.4.0)

**Comment by giuliopaci** [comment]
This is so since a long time. The software has been tweaked explicitly to
be able to work with both old and new compilers according to the results of
these checks (with standard/new approach being the default).

The correct fix is to install missing macros, as I suggested, or to drop
backward compatibility, which is probably fine as well.
Il giorno 06/dic/2017 12:41, "Karel Vesely" <notifications@github.com> ha
scritto:

**Comment by giuliopaci** [comment]
I listed autoconf-archive among requirements in README.
As autoconf-archive is easily available on major development platforms (including Linux distributions, Mac OSX and Windows), I consider this issue solved.

If you think a different solution is needed, feel free to reopen this issue and provide further information.
